baseurl = "https://gallant-volhard-497d9d.netlify.com/"
title = "Hugo Test"
copyright = "Copyright &copy; 2019 - Ilia Frenkel"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Ilia Frenkel"
    github = "iliafrenkel"
    gitlab = ""
    linkedin = "iliafrenkel"
    facebook = "ilia.frenkel"
    twitter = "iliafrenkel"
    instagram = "iliafrenkel"

[params]
    tagline = "A Hugo test for creative and technical writing"

[[menu.main]]
    name = "Home"
    weight = 10
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
